### ISSUE TITLE
wireless filemanager crashed (androind TV 10)

### ISSUE THREAD

**Issue by B3rt** [visnkmr/wfm#1]
I installed it on my philips android TV running android 10.

When i start the APP it tuns aprox 10 seconds and then crashes, i simply cannot get it to run.
It displays the IP and after a 10 seconds the connection is closed and i have to start the wireless connection again.

**Comment by visnkmr** [comment]
Hey,
Since your TV is running on Android 10; The version of the app you are using should be 2.241G. The latest version of the app that is in active development is 2.3G; it is available on Amazon Appstore for everyone and on Google Play store for android 11 and above. We do have members of our family running v2.241G of the app consistently on their Android TV running on Android 10 and have never encountered the issue thus far. But owing to your experience we will actively keep an eye out for issues in the future. And will update here once we encounter/fix the issue.
