### ISSUE TITLE
Push 2.3A8i update to Android TV

### ISSUE THREAD

**Issue by Ajay-056** [visnkmr/wfm#222]
There are lots of bugs and compatibility issues in older version. Pushing latest update would resolve such issues

**Comment by visnkmr** [comment]
Hey, 
The Google Play store version of the app is no longer available 

This is because of various issues relating to developer distribution experience provided by Play store.
These include
- lack of meaningful communication regarding policy violations,
- continous breaking changes to API being used by the app, 

if you so prefer you can also download from our appstore/github @ https://vnkappstore.vercel.app/details/Wireless%20File%20Manager
https://visnkmr.github.io/appstore/details/Wireless%20File%20Manager
https://github.com/visnkmr/wfm/releases
