### ISSUE TITLE
Unable to use the file explorer in the app

### ISSUE THREAD

**Issue by sun1595** [visnkmr/wfm#3]
Hi Vishnu,

First of all, it's great to have a single app installed that has file explorer and wireless file transfer built in. My device is nokia media streamer running on android 9 pie. I installed the app via play store and tried to browse files via the file explorer but it shows only one folder inside and then i get a message No Items Found. It stays in the Recent files window by default with no option to go back or navigate to other folders. However the wireless file manager is working without any issues. I was able to upload some apk's from my laptop and it was successfully received. The file explorer lists those received files in the recent files window when i open it as mentioned above. How do i solve the file explorer issue?

**Comment by visnkmr** [comment]
Hey,
Hope you have found our app useful. 

Wireless File Manager's File explorer allows you to browse the file you transferred to device using Wireless File Manager's Web UI and the files transferred via a file manager to the apps files folder (/Android/data/io.github.visnkmr.wirelessexplorer/files/data). The option to view all files stored was present in our app previously but was later separated into a separate file explorer app to push updates faster and later this file explorer app was pulled from google play since the android APIs required to handle files on android has had major fundamental changes and documentation for the changes remain scarce and remains segregated based on the android version. We do hope to bring back the app on Google play in the future. The file explorer app is still available via amazon appstore if you wish to try it out.
