### ISSUE TITLE
App is saying  its out dated but it is on latest version 

### ISSUE THREAD

**Issue by manofsteel2017** [visnkmr/wfm#328]
Both android and android tv version showing outdated message, asking to update or change that time.
Both are on latest version and time is correct

**Comment by visnkmr** [comment]
Hey, The app has been not updated on Google play, since October 2023, and is no longer available for download by new users. It is available on Amazon appstore. You can find it on our [appstore](https://visnkmr.github.io/appstore) as well. With regards to downloading apps from amazon appstore, sometimes even though it shows as having installed the latest version it installs an older version of the app, this is user specific in most cases. We will already reported this to amazon, but haven't heard back from them in a long time. The only way to check if the latest version is installed is to check the version number installed.
